name: CI
on: push


jobs:
  install:
    name: Install as rez package (${{ matrix.os }} py${{ matrix.python }})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python: [2.7, 3.7]
        os: [ubuntu, windows]
        include:
        - {os: ubuntu,  variant: 0, exe: katana}
        - {os: windows,  variant: 1, exe: katanaBin.exe}

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - uses: j0yu/setup-rez@v1

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v2

    - run: rez build --install --variant ${{ matrix.variant }}

    - run: rez env katana -- which ${{ matrix.exe }}
